export const COMPLAINT_CREATE_REQUEST = "COMPLAINT_CREATE_REQUEST";
export const COMPLAINT_CREATE_SUCCESS = "COMPLAINT_CREATE_SUCCESS";
export const COMPLAINT_CREATE_FAIL = "COMPLAINT_CREATE_FAIL";
export const COMPLAINT_CREATE_RESET = "COMPLAINT_CREATE_RESET";

export const COMPLAINT_LIST_REQUEST = "COMPLAINT_LIST_REQUEST";
export const COMPLAINT_LIST_SUCCESS = "COMPLAINT_LIST_SUCCESS";
export const COMPLAINT_LIST_FAIL = "COMPLAINT_LIST_FAIL";
export const COMPLAINT_LIST_RESET = "COMPLAINT_LIST_RESET";

export const COMPLAINT_MY_REQUEST = "COMPLAINT_MY_REQUEST";
export const COMPLAINT_MY_SUCCESS = "COMPLAINT_MY_SUCCESS";
export const COMPLAINT_MY_FAIL = "COMPLAINT_MY_FAIL";
export const COMPLAINT_MY_RESET = "COMPLAINT_MY_RESET";

export const COMPLAINT_ASSIGNED_REQUEST = "COMPLAINT_ASSIGNED_REQUEST";
export const COMPLAINT_ASSIGNED_SUCCESS = "COMPLAINT_ASSIGNED_SUCCESS";
export const COMPLAINT_ASSIGNED_FAIL = "COMPLAINT_ASSIGNED_FAIL";
export const COMPLAINT_ASSIGNED_RESET = "COMPLAINT_ASSIGNED_RESET";

export const COMPLAINT_DETAILS_REQUEST = "COMPLAINT_DETAILS_REQUEST";
export const COMPLAINT_DETAILS_SUCCESS = "COMPLAINT_DETAILS_SUCCESS";
export const COMPLAINT_DETAILS_FAIL = "COMPLAINT_DETAILS_FAIL";
export const COMPLAINT_DETAILS_RESET = "COMPLAINT_DETAILS_RESET";

export const COMPLAINT_UPDATE_REQUEST = "COMPLAINT_UPDATE_REQUEST";
export const COMPLAINT_UPDATE_SUCCESS = "COMPLAINT_UPDATE_SUCCESS";
export const COMPLAINT_UPDATE_FAIL = "COMPLAINT_UPDATE_FAIL";
export const COMPLAINT_UPDATE_RESET = "COMPLAINT_UPDATE_RESET";

export const COMPLAINT_FEEDBACK_REQUEST = "COMPLAINT_FEEDBACK_REQUEST";
export const COMPLAINT_FEEDBACK_SUCCESS = "COMPLAINT_FEEDBACK_SUCCESS";
export const COMPLAINT_FEEDBACK_FAIL = "COMPLAINT_FEEDBACK_FAIL";
export const COMPLAINT_FEEDBACK_RESET = "COMPLAINT_FEEDBACK_RESET";

export const COMPLAINT_STATS_REQUEST = "COMPLAINT_STATS_REQUEST";
export const COMPLAINT_STATS_SUCCESS = "COMPLAINT_STATS_SUCCESS";
export const COMPLAINT_STATS_FAIL = "COMPLAINT_STATS_FAIL";
export const COMPLAINT_STATS_RESET = "COMPLAINT_STATS_RESET";
